application: expense--tracker
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /bootstrap
  static_dir: src/bootstrap

- url: /
  script: src/home.app

- url: /.*
  script: src/main.app
  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
