application: expense--tracker
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: assets/favicon.ico
  upload: favicon\.ico

- url: /bootstrap
  static_dir: assets/bootstrap

- url: /
  script: home.app

- url: /.*
  script: example.app
  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
