application: genuine-flight-91402
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /processpayment
  script: processpayment.app

- url: /
  static_dir: frontend

libraries:
- name: webapp2
  version: latest
